version: "3.4"

services:
  eshop.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://root:example@eshop.mongodb:27017/?authSource=admin
      - MongoDB__DatabaseName=OrdersDb
      - productApi=http://wiremock.gui:8080
    ports:
      - "8080:80"
    depends_on:
      - eshop.mongodb
      - wiremock.gui
    networks:
      - my-network

  eshop.mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - my-network

  wiremock.gui:
    image: holomekc/wiremock-gui
    ports:
      - "8081:8080" # Change the host port if needed
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
